export const TRACKS_SET = 'TRACKS_SET';
export const SET_AMENITIES = 'SET_AMENITIES';
export const ADD_TO_CHECKED_AMENITIES = 'ADD_TO_CHECKED_AMENITIES';
export const SET_APARTMENTS = 'SET_APARTMENTS';